"""LCM type definitions
This file automatically generated by lcm.
DO NOT MODIFY BY HAND!!!!
"""

try:
    import cStringIO.StringIO as BytesIO
except ImportError:
    from io import BytesIO
import struct

import frankalcm.bool

class robot_command(object):
    __slots__ = ["robot_enable"]

    __typenames__ = ["frankalcm.bool"]

    __dimensions__ = [None]

    def __init__(self):
        self.robot_enable = frankalcm.bool()

    def encode(self):
        buf = BytesIO()
        buf.write(robot_command._get_packed_fingerprint())
        self._encode_one(buf)
        return buf.getvalue()

    def _encode_one(self, buf):
        assert self.robot_enable._get_packed_fingerprint() == frankalcm.bool._get_packed_fingerprint()
        self.robot_enable._encode_one(buf)

    def decode(data):
        if hasattr(data, 'read'):
            buf = data
        else:
            buf = BytesIO(data)
        if buf.read(8) != robot_command._get_packed_fingerprint():
            raise ValueError("Decode error")
        return robot_command._decode_one(buf)
    decode = staticmethod(decode)

    def _decode_one(buf):
        self = robot_command()
        self.robot_enable = frankalcm.bool._decode_one(buf)
        return self
    _decode_one = staticmethod(_decode_one)

    _hash = None
    def _get_hash_recursive(parents):
        if robot_command in parents: return 0
        newparents = parents + [robot_command]
        tmphash = (0xf3aa78b9bece8c45+ frankalcm.bool._get_hash_recursive(newparents)) & 0xffffffffffffffff
        tmphash  = (((tmphash<<1)&0xffffffffffffffff) + (tmphash>>63)) & 0xffffffffffffffff
        return tmphash
    _get_hash_recursive = staticmethod(_get_hash_recursive)
    _packed_fingerprint = None

    def _get_packed_fingerprint():
        if robot_command._packed_fingerprint is None:
            robot_command._packed_fingerprint = struct.pack(">Q", robot_command._get_hash_recursive([]))
        return robot_command._packed_fingerprint
    _get_packed_fingerprint = staticmethod(_get_packed_fingerprint)

