"""LCM type definitions
This file automatically generated by lcm.
DO NOT MODIFY BY HAND!!!!
"""

try:
    import cStringIO.StringIO as BytesIO
except ImportError:
    from io import BytesIO
import struct

class robot_command(object):
    __slots__ = ["tau_J_d", "loop_closed"]

    __typenames__ = ["double", "boolean"]

    __dimensions__ = [[7], None]

    def __init__(self):
        self.tau_J_d = [ 0.0 for dim0 in range(7) ]
        self.loop_closed = False

    def encode(self):
        buf = BytesIO()
        buf.write(robot_command._get_packed_fingerprint())
        self._encode_one(buf)
        return buf.getvalue()

    def _encode_one(self, buf):
        buf.write(struct.pack('>7d', *self.tau_J_d[:7]))
        buf.write(struct.pack(">b", self.loop_closed))

    def decode(data):
        if hasattr(data, 'read'):
            buf = data
        else:
            buf = BytesIO(data)
        if buf.read(8) != robot_command._get_packed_fingerprint():
            raise ValueError("Decode error")
        return robot_command._decode_one(buf)
    decode = staticmethod(decode)

    def _decode_one(buf):
        self = robot_command()
        self.tau_J_d = struct.unpack('>7d', buf.read(56))
        self.loop_closed = bool(struct.unpack('b', buf.read(1))[0])
        return self
    _decode_one = staticmethod(_decode_one)

    def _get_hash_recursive(parents):
        if robot_command in parents: return 0
        tmphash = (0x8ac804e7a94a1f14) & 0xffffffffffffffff
        tmphash  = (((tmphash<<1)&0xffffffffffffffff) + (tmphash>>63)) & 0xffffffffffffffff
        return tmphash
    _get_hash_recursive = staticmethod(_get_hash_recursive)
    _packed_fingerprint = None

    def _get_packed_fingerprint():
        if robot_command._packed_fingerprint is None:
            robot_command._packed_fingerprint = struct.pack(">Q", robot_command._get_hash_recursive([]))
        return robot_command._packed_fingerprint
    _get_packed_fingerprint = staticmethod(_get_packed_fingerprint)

    def get_hash(self):
        """Get the LCM hash of the struct"""
        return struct.unpack(">Q", robot_command._get_packed_fingerprint())[0]

