"""LCM type definitions
This file automatically generated by lcm.
DO NOT MODIFY BY HAND!!!!
"""

try:
    import cStringIO.StringIO as BytesIO
except ImportError:
    from io import BytesIO
import struct

class gripper_state(object):
    __slots__ = ["width"]

    __typenames__ = ["double"]

    __dimensions__ = [None]

    def __init__(self):
        self.width = 0.0

    def encode(self):
        buf = BytesIO()
        buf.write(gripper_state._get_packed_fingerprint())
        self._encode_one(buf)
        return buf.getvalue()

    def _encode_one(self, buf):
        buf.write(struct.pack(">d", self.width))

    def decode(data):
        if hasattr(data, 'read'):
            buf = data
        else:
            buf = BytesIO(data)
        if buf.read(8) != gripper_state._get_packed_fingerprint():
            raise ValueError("Decode error")
        return gripper_state._decode_one(buf)
    decode = staticmethod(decode)

    def _decode_one(buf):
        self = gripper_state()
        self.width = struct.unpack(">d", buf.read(8))[0]
        return self
    _decode_one = staticmethod(_decode_one)

    _hash = None
    def _get_hash_recursive(parents):
        if gripper_state in parents: return 0
        tmphash = (0x4cab859bcaca965e) & 0xffffffffffffffff
        tmphash  = (((tmphash<<1)&0xffffffffffffffff) + (tmphash>>63)) & 0xffffffffffffffff
        return tmphash
    _get_hash_recursive = staticmethod(_get_hash_recursive)
    _packed_fingerprint = None

    def _get_packed_fingerprint():
        if gripper_state._packed_fingerprint is None:
            gripper_state._packed_fingerprint = struct.pack(">Q", gripper_state._get_hash_recursive([]))
        return gripper_state._packed_fingerprint
    _get_packed_fingerprint = staticmethod(_get_packed_fingerprint)

